#!/usr/bin/env bash
# smoke tests for sandboxed-copilot
#
# Tests:
#   1. Both Docker images build successfully
#   2. Expected tools are present and executable (gh, mise)
#   3. Container runs as root with cap_drop: ALL (zero Linux capabilities)
#   4. Proxy allows connections to allowlisted domains (github.com)
#   5. Proxy blocks connections to non-allowlisted domains (example.com)
#   6. Direct internet bypass is impossible (no route around the proxy)
#   7. Allowlist live-reload: a newly added domain becomes reachable within 10s
#   8. copilot-cli binary is present in the image
#   9. Home directory files are owned by root
#  10. TLS inspection (ssl_bump): CA cert is installed in the copilot trust store
#  11. TLS inspection (ssl_bump): HTTPS succeeds with HTTP 200 AND cert is signed by CA
#  12. Auth status detection handles missing token gracefully
#  13. proxy denied lists blocked domains and excludes allowlisted ones
#  14. Proxy container is still running with zero restarts after all tests
#
# Usage:
#   bash test/smoke.sh            # from project root
#   cd test && bash smoke.sh      # from test directory

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMPOSE_FILE="${PROJECT_DIR}/docker-compose.yml"
ALLOWLIST="${PROJECT_DIR}/config/allowlist.txt"

# Compute the session hash the same way the launcher does (cksum of workspace path).
# This ensures the test's docker compose project name matches what the launcher
# would derive when run from PROJECT_DIR, so proxy denied can find the right container.
_test_hash=$(printf '%s' "$PROJECT_DIR" | cksum | awk '{printf "%08d", $1}')
TEST_PROJECT_NAME="sandboxed-copilot-${_test_hash}"
export PROJECT_ALLOWLIST_FILE="project-allowlist-${_test_hash}.txt"
export COPILOT_WORKSPACE="${PROJECT_DIR}"

COMPOSE="docker compose -f ${COMPOSE_FILE} --project-directory ${PROJECT_DIR} --project-name ${TEST_PROJECT_NAME}"

PASS=0
FAIL=0
declare -a ERRORS=()

# ── Helpers ───────────────────────────────────────────────────────────────────

pass() { echo "  ✓ $*"; PASS=$((PASS + 1)); }
fail() { echo "  ✗ $*"; FAIL=$((FAIL + 1)); ERRORS+=("$*"); }

# Run a command inside the copilot container without starting the proxy.
# Use for tests that don't need network access.
run_offline() {
    $COMPOSE run --rm --no-deps copilot bash -c "$1" 2>/dev/null
}

# Run a command inside the copilot container with the proxy active.
run_online() {
    $COMPOSE run --rm copilot bash -c "$1" 2>/dev/null
}

cleanup() {
    echo ""
    echo "── Cleaning up..."
    $COMPOSE down --volumes --remove-orphans 2>/dev/null || true
    # Remove the test session's project-allowlist file.
    rm -f "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}" 2>/dev/null || true
    # Restore allowlist if we modified it
    if [ -n "${ALLOWLIST_BACKUP:-}" ]; then
        # printf '%s\n' restores the trailing newline stripped by $(cat ...).
        printf '%s\n' "$ALLOWLIST_BACKUP" > "$ALLOWLIST"
    fi
    # Remove test-generated CA cert/key if we created them.
    if [ "${_test_generated_ca:-false}" = true ]; then
        rm -f "${PROJECT_DIR}/config/ca.crt" "${PROJECT_DIR}/config/ca.key" 2>/dev/null || true
    fi
}
trap cleanup EXIT

# Wait for the proxy container to report a healthy status, or fail after timeout.
# Exits 0 on healthy, 1 on unhealthy or timeout.
wait_for_proxy_healthy() {
    local max_wait=90
    local elapsed=0
    echo "    Waiting for proxy to become healthy (up to ${max_wait}s)..."
    local cid
    # Give the container a moment to appear
    sleep 2
    cid=$($COMPOSE ps -q proxy 2>/dev/null | head -1 | tr -d '[:space:]')
    if [ -z "$cid" ]; then
        echo "  ✗ Proxy container not found — did docker compose up succeed?"
        return 1
    fi
    while [ $elapsed -lt $max_wait ]; do
        local health
        health=$(docker inspect --format='{{.State.Health.Status}}' "$cid" 2>/dev/null || echo "unknown")
        case "$health" in
            healthy)
                echo "    Proxy is healthy (${elapsed}s)"
                return 0
                ;;
            unhealthy)
                echo "  ✗ Proxy healthcheck reports unhealthy after ${elapsed}s"
                echo "    Recent proxy logs:"
                $COMPOSE logs --tail=20 proxy 2>/dev/null | sed 's/^/    /'
                return 1
                ;;
        esac
        sleep 3
        elapsed=$((elapsed + 3))
    done
    echo "  ✗ Proxy did not become healthy within ${max_wait}s"
    echo "    Recent proxy logs:"
    $COMPOSE logs --tail=20 proxy 2>/dev/null | sed 's/^/    /'
    return 1
}

# ---------------------------------------------------------------------------
# The proxy requires config/ca.crt and config/ca.key (generated by install.sh).
# For test runs directly from the repo (without install.sh having been run),
# generate a throwaway CA cert with a short validity period.
# ---------------------------------------------------------------------------
_test_generated_ca=false
if [ ! -f "${PROJECT_DIR}/config/ca.crt" ] || [ ! -f "${PROJECT_DIR}/config/ca.key" ]; then
    echo "── Generating temporary CA cert for test run..."
    if ! command -v openssl >/dev/null 2>&1; then
        echo "  ✗ openssl is required to generate a temporary CA cert, but was not found."
        exit 1
    fi
    if openssl req -new -newkey rsa:2048 -days 1 -nodes -x509 \
        -subj "/CN=sandboxed-copilot test CA/O=sandboxed-copilot" \
        -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" \
        -keyout "${PROJECT_DIR}/config/ca.key" \
        -out "${PROJECT_DIR}/config/ca.crt" \
        2>/dev/null; then
        chmod 600 "${PROJECT_DIR}/config/ca.key"
        _test_generated_ca=true
        echo ""
    else
        echo "  ✗ Failed to generate temporary CA cert/key with openssl."
        exit 1
    fi
fi

# ── 1. Build ─────────────────────────────────────────────────────────────────

echo "=== sandboxed-copilot smoke tests ==="
echo ""
echo "── 1. Building images..."

if $COMPOSE build 2>&1; then
    pass "Both images built successfully"
else
    fail "Image build failed"
    echo ""
    echo "Build failed — cannot continue."
    exit 1
fi
echo ""

# ── 2. Tool availability ──────────────────────────────────────────────────────

echo "── 2. Checking installed tools..."

if run_offline "which gh >/dev/null 2>&1"; then
    pass "gh CLI is on PATH"
else
    fail "gh CLI not found on PATH"
fi

if run_offline "gh --version >/dev/null 2>&1"; then
    pass "gh CLI executes"
else
    fail "gh CLI does not execute"
fi

if run_offline "which mise >/dev/null 2>&1"; then
    pass "mise is on PATH"
else
    fail "mise not found on PATH"
fi

if run_offline "mise --version >/dev/null 2>&1"; then
    pass "mise executes"
else
    fail "mise does not execute"
fi

echo ""

# ── 3. Root user + zero capabilities ─────────────────────────────────────────

echo "── 3. Checking runtime user and capabilities..."

CURRENT_USER=$(run_offline "whoami" 2>/dev/null | tr -d '[:space:]')
if [ "$CURRENT_USER" = "root" ]; then
    pass "Runs as root (security model: root + cap_drop: ALL)"
else
    fail "Expected root user (root + cap_drop: ALL model), got: '${CURRENT_USER}'"
fi

CURRENT_UID=$(run_offline "id -u" 2>/dev/null | tr -d '[:space:]')
if [ "$CURRENT_UID" = "0" ]; then
    pass "UID is 0 (root)"
else
    fail "Unexpected UID: '${CURRENT_UID}' (expected 0)"
fi

# Verify ALL capabilities are dropped (cap_drop: ALL in docker-compose.yml).
# capsh --print parses /proc/self/status. With cap_drop: ALL, CapEff should be 0.
CAP_EFF=$(run_offline "cat /proc/self/status | grep CapEff" 2>/dev/null | awk '{print $2}' | tr -d '[:space:]')
if [ "$CAP_EFF" = "0000000000000000" ]; then
    pass "Effective capabilities are all zero (cap_drop: ALL confirmed)"
else
    fail "Unexpected effective capabilities: CapEff=${CAP_EFF} (expected 0000000000000000)"
fi

echo ""

# ── 4-6. Firewall ─────────────────────────────────────────────────────────────

echo "── 4-6. Starting proxy for firewall tests..."
$COMPOSE up -d proxy 2>/dev/null
if ! wait_for_proxy_healthy; then
    fail "Proxy did not start or become healthy — cannot run network tests"
    exit 1
fi
echo ""

echo "── 4. Allowed domain reachable..."
if run_online "curl -sf --max-time 15 https://github.com -o /dev/null 2>&1"; then
    pass "github.com is reachable and HTTPS succeeds (CA cert trusted, allowlist active)"
else
    fail "github.com is NOT reachable — proxy may be misconfigured or CA cert not trusted"
fi

echo ""
echo "── 5. Non-allowlisted domain blocked..."
# example.com is not in the default allowlist
if run_online "curl -sf --max-time 10 https://example.com -o /dev/null 2>/dev/null"; then
    fail "example.com is reachable — firewall is NOT blocking non-allowlisted traffic"
else
    pass "example.com is blocked by the proxy (not in allowlist)"
fi

echo ""
echo "── 6. Direct internet bypass blocked..."
# --noproxy '*' tells curl to ignore HTTP_PROXY / HTTPS_PROXY.
# The copilot container is on an internal-only Docker network so direct
# connections should fail even without the proxy.
if run_online "curl -sf --max-time 8 --noproxy '*' https://github.com -o /dev/null 2>/dev/null"; then
    fail "Direct internet access succeeded — the container has an unexpected route bypassing the proxy"
else
    pass "Direct internet access is blocked (internal-only network enforced)"
fi

echo ""

# ── 7. Allowlist live-reload ──────────────────────────────────────────────────

echo "── 7. Testing allowlist live-reload..."

# Save current allowlist so we can restore it
ALLOWLIST_BACKUP="$(cat "$ALLOWLIST")"

# Add example.com to the allowlist
echo "example.com" >> "$ALLOWLIST"
echo "    Added example.com to allowlist — waiting up to 10s for squid reload..."
sleep 10

if run_online "curl -sf --max-time 10 http://example.com -o /dev/null 2>/dev/null"; then
    pass "Newly added domain (example.com) is reachable after live reload"
else
    fail "Newly added domain (example.com) not reachable after 10s — live reload may not be working"
fi

# Restore the original allowlist
# Restore the original allowlist; printf '%s\n' adds back the trailing newline
# that command substitution strips.
printf '%s\n' "$ALLOWLIST_BACKUP" > "$ALLOWLIST"

echo ""

# ── 8. Copilot CLI binary present in image ────────────────────────────────────
# The copilot-cli binary is baked into the Docker image at build time, so it
# must be present and executable without any network access or volume mounting.
# `gh copilot` (built-in) looks for this binary at this exact path.

echo "── 8. Verifying copilot-cli binary is baked into the image..."

COPILOT_BIN="/home/copilot/.local/share/gh/copilot/copilot"
COPILOT_OUTPUT=$(run_offline "test -x '$COPILOT_BIN' && echo present || echo absent" 2>/dev/null | tr -d '[:space:]')
if [ "$COPILOT_OUTPUT" = "present" ]; then
    pass "copilot-cli binary is present and executable in the image"
else
    fail "copilot-cli binary is missing from the image (was it installed at build time?)"
fi

echo ""

# ── 9. Home directory ownership ───────────────────────────────────────────────

echo "── 9. Checking home directory ownership..."

# All files under /home/copilot should be owned by root — the container runs
# as root with cap_drop: ALL providing containment.
NOT_ROOT_OWNED=$(run_offline "find /home/copilot -not -user root 2>/dev/null | head -5" 2>/dev/null | tr -d '[:space:]')
if [ -z "$NOT_ROOT_OWNED" ]; then
    pass "All files in /home/copilot are owned by root"
else
    fail "Some files in /home/copilot are not owned by root: ${NOT_ROOT_OWNED}"
fi

echo ""

# ── 10. TLS inspection (ssl_bump) ─────────────────────────────────────────────

echo "── 10. Testing ssl_bump CA cert trust..."

# A per-install CA cert is generated on the host and mounted into the containers.
# The entrypoint installs that mounted CA into the system trust store via update-ca-certificates.
# After the entrypoint runs, the mounted CA should appear in the system trust store.
CA_INSTALLED=$(run_online \
    "test -f /etc/ssl/certs/sandboxed-copilot-ca.pem && echo installed || echo missing" \
    2>/dev/null | tr -d '[:space:]')

if [ "$CA_INSTALLED" = "installed" ]; then
    pass "ssl_bump CA cert is installed in the copilot container trust store"
else
    fail "ssl_bump CA cert not found in trust store (/etc/ssl/certs/sandboxed-copilot-ca.pem)"
fi

echo ""

# ── 11. ssl_bump TLS interception ────────────────────────────────────────────
#
# Verify that the proxy is actually intercepting HTTPS connections, not just
# tunnelling them. With ssl_bump active:
#   - The copilot container sees a certificate signed by our per-install CA
#   - curl trusts this cert (because our CA is in the system trust store)
#   - The issuer in the certificate chain contains "sandboxed-copilot"
#
# This test requires the proxy to be running and ssl_bump to be operational.
# It will fail if Squid fell back to CONNECT tunnelling or if the sslcrtd
# helper crashed (which was the bug that prompted this test).

echo "── 11. Testing ssl_bump TLS interception..."

# ssl_bump end-to-end test: verify two things in a single container invocation:
#   a) curl exits 0 — HTTPS request succeeds end-to-end, confirming the CA cert
#      is installed and trusted. Would fail with exit 60 (SSL verify error) if
#      the CA cert was not in the trust store (caught the update-ca-certificates
#      -q bug that caused silent install failure).
#   b) The certificate issuer contains "sandboxed-copilot" — confirms the proxy
#      is actively intercepting (ssl_bump), not just tunnelling (CONNECT).
#      Would fail if sslcrtd crashed and Squid fell back to tunnel mode
#      (caught the ssl_db EEXIST bug that silently killed sslcrtd).
#
# Using github.com (same domain as test 4) for consistency and reliability.

if TLS_INFO=$(run_online "curl -sv --max-time 15 https://github.com -o /dev/null 2>&1" 2>/dev/null); then
    if echo "$TLS_INFO" | grep -qi "issuer.*sandboxed-copilot"; then
        pass "ssl_bump e2e: HTTPS succeeds and certificate is issued by sandboxed-copilot CA"
    else
        ISSUER_LINE=$(echo "$TLS_INFO" | grep -i "issuer" | head -1)
        fail "ssl_bump e2e: HTTPS succeeded but issuer is NOT sandboxed-copilot CA: '${ISSUER_LINE:-no issuer line found}'"
    fi
else
    CURL_ERR=$(echo "$TLS_INFO" | grep -i "curl:" | head -1)
    fail "ssl_bump e2e: HTTPS request failed: '${CURL_ERR:-no curl error line, TLS_INFO=${TLS_INFO}}'"
fi

echo ""

# ── 12. Auth banner — unauthenticated path ────────────────────────────────────

echo "── 12. Testing auth status detection..."

# Verify the container handles a missing/invalid token gracefully.
# When GITHUB_TOKEN is empty, the entrypoint should fall back to "Not authenticated".
AUTH_OFFLINE=$($COMPOSE run --rm --no-deps \
    -e GITHUB_TOKEN="" \
    copilot bash -c \
    'gh_login=$(GITHUB_TOKEN="" gh api /user --jq .login 2>/dev/null || true)
     if [ -n "$gh_login" ]; then echo "authenticated:$gh_login"; else echo "not_authenticated"; fi' \
    2>/dev/null | tr -d '[:space:]')

if [ "$AUTH_OFFLINE" = "not_authenticated" ]; then
    pass "Auth check returns 'not authenticated' gracefully when GITHUB_TOKEN is empty"
else
    fail "Unexpected auth check result with empty token: '${AUTH_OFFLINE}'"
fi

# If a real GITHUB_TOKEN is available, verify it resolves to a login.
if [ -n "${GITHUB_TOKEN:-}" ]; then
    AUTH_ONLINE=$(run_online \
        'gh_login=$(gh api /user --jq .login 2>/dev/null || true); echo "${gh_login:-empty}"' \
        2>/dev/null | tr -d '[:space:]')
    if [ -n "$AUTH_ONLINE" ] && [ "$AUTH_ONLINE" != "empty" ]; then
        pass "Auth check resolves GitHub login: @${AUTH_ONLINE}"
    else
        fail "Auth check failed to resolve login despite GITHUB_TOKEN being set"
    fi
else
    echo "  ⚠ GITHUB_TOKEN not set — skipping authenticated auth check"
fi

echo ""

# ── 13. proxy denied command ──────────────────────────────────────────────────

echo "── 13. Testing proxy denied command..."

# The proxy should still be running from the firewall tests.
# Make a request to a non-allowlisted domain so it appears in the Squid deny log.
run_online "curl -sf --max-time 5 https://blocked-domain-for-test.example.com -o /dev/null 2>/dev/null" || true
# Give squid a moment to flush the log entry.
sleep 2

# Call the launcher with the test project's workspace so the hash-derived project
# name matches the test project. SANDBOXED_COPILOT_DIR points at the repo root
# (which doubles as the install dir for tests).
DENIED_OUTPUT=$(cd "$PROJECT_DIR" && \
    SANDBOXED_COPILOT_DIR="$PROJECT_DIR" \
    bash "$PROJECT_DIR/sandboxed-copilot" proxy denied --all 2>/dev/null || true)

if echo "$DENIED_OUTPUT" | grep -q "blocked-domain-for-test.example.com"; then
    pass "proxy denied lists domains blocked by the proxy"
else
    fail "proxy denied did not include the expected blocked domain (got: '${DENIED_OUTPUT}')"
fi

# Allowlisted domains must NOT appear in the output.
if echo "$DENIED_OUTPUT" | grep -q "github.com"; then
    fail "proxy denied incorrectly listed an allowlisted domain (github.com)"
else
    pass "proxy denied correctly excludes allowlisted domains"
fi

echo ""

# ── 14. Proxy container stability ─────────────────────────────────────────────
#
# After all network tests, the proxy should still be running with zero restarts.
# A non-zero restart count indicates the proxy crashed and was restarted by Docker
# at some point during the test run — a sign of intermittent failure.

echo "── 14. Checking proxy container stability..."

PROXY_CID=$($COMPOSE ps -q proxy 2>/dev/null | head -1 | tr -d '[:space:]')
if [ -n "$PROXY_CID" ]; then
    PROXY_STATUS=$(docker inspect --format='{{.State.Status}}' "$PROXY_CID" 2>/dev/null || echo "unknown")
    PROXY_RESTARTS=$(docker inspect --format='{{.RestartCount}}' "$PROXY_CID" 2>/dev/null || echo "unknown")
    if [ "$PROXY_STATUS" = "running" ] && [ "$PROXY_RESTARTS" = "0" ]; then
        pass "Proxy container is running with zero restarts (stable)"
    else
        fail "Proxy is unstable: status=${PROXY_STATUS}, restarts=${PROXY_RESTARTS}"
    fi
else
    fail "Proxy container not found — may have exited"
fi

echo ""

# ── 15. Token exfiltration — header detection ────────────────────────────────
#
# Verify that the Squid ACL detects a GitHub-format token in the Authorization
# header and blocks the request even when the destination domain IS in the
# allowlist. This proves the exfil rule fires independently of the allowlist.
#
# We temporarily add a test domain to the project allowlist and confirm that
# (a) a request WITHOUT a token to that domain would be allowed (so the block
#     really is due to the token, not just the allowlist), and
# (b) a request WITH a fake GitHub token is blocked and appears in exfil.log.
#
# The fake token uses the ghp_ prefix with 36 'x' chars (total 40 chars) which
# matches the real token format but will never authenticate anywhere.

echo "── 15. Testing token exfiltration header detection..."

# Both header and body exfil tests require a resolvable domain: ssl_bump must
# establish an upstream connection before Squid can inspect inner HTTPS headers
# or call the ICAP adapter. The exfil ACL (header) / ICAP scanner (body) blocks
# before the origin response matters, so the domain's actual content is irrelevant.
EXFIL_TEST_DOMAIN="example.com"
ICAP_TEST_DOMAIN="example.com"
FAKE_TOKEN="ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Temporarily allow the test domain so we can prove the exfil ACL overrides it.
echo "${EXFIL_TEST_DOMAIN}" >> "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}"
sleep 3  # wait for squid to pick up the allowlist change

# Clear any prior exfil.log entries for a clean baseline.
PROXY_CID=$($COMPOSE ps -q proxy 2>/dev/null | head -1 | tr -d '[:space:]')

# A plain request to the test domain (no token) should succeed but the proxy
# should NOT add it to exfil.log. We only check that the token-bearing request
# IS in exfil.log.

# Make the request with a fake token in the Authorization header.
# curl may fail or succeed depending on origin response — that's irrelevant;
# the exfil ACL blocks the request before it reaches the origin.
run_online "curl -sf --max-time 5 \
    -H 'Authorization: token ${FAKE_TOKEN}' \
    https://${EXFIL_TEST_DOMAIN}/ -o /dev/null 2>/dev/null" || true
sleep 2

# Check that the exfil.log inside the proxy container recorded this attempt.
EXFIL_ENTRY=$(docker exec "$PROXY_CID" \
    grep -c "${EXFIL_TEST_DOMAIN}" /var/log/squid/exfil.log 2>/dev/null || echo "0")

if [ "${EXFIL_ENTRY:-0}" -gt 0 ]; then
    pass "Token exfiltration (header): blocked and recorded in exfil.log"
else
    fail "Token exfiltration (header): expected exfil.log entry for ${EXFIL_TEST_DOMAIN}, got none"
fi

# Remove the test domain from the project allowlist.
# Use portable in-place editing (no sed -i on macOS without backup extension).
ALLOWLIST_TMP=$(mktemp)
grep -v "^${EXFIL_TEST_DOMAIN}$" "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}" > "$ALLOWLIST_TMP" || true
mv "$ALLOWLIST_TMP" "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}"

echo ""

# ── 16. Token exfiltration — body detection (ICAP) ───────────────────────────
#
# Verify that the ICAP scanner detects a GitHub-format token in a POST request
# body and blocks the request. The ICAP scanner is responsible for body scanning;
# this test confirms it is running and intercepting POST/PUT/PATCH requests.
#
# Same approach as test 15: temporarily allow the test domain, send a POST with
# a token in the body, verify the ICAP scanner logged it in exfil.log.

echo "── 16. Testing token exfiltration body detection (ICAP)..."

# Use a resolvable domain: ICAP body scanning runs after DNS resolves the
# upstream connection, so the test domain must actually resolve. The ICAP
# scanner will block the request before it reaches the origin server.
# Add to the correct per-session project allowlist (same file the proxy reads).
echo "${ICAP_TEST_DOMAIN}" >> "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}"
sleep 3

# Make a POST with the token embedded in a JSON-like body (no Authorization header
# this time, so only the body scanner can catch it).
run_online "curl -sf --max-time 5 \
    -X POST \
    -H 'Content-Type: application/json' \
    -d '{\"access_token\":\"${FAKE_TOKEN}\",\"data\":\"exfil-test\"}' \
    https://${ICAP_TEST_DOMAIN}/ -o /dev/null 2>/dev/null" || true
sleep 2

# Count ICAP entries for this domain — we expect at least one.
# Use "; true" inside sh -c so grep's exit code (1 on no match) doesn't cause
# the command substitution to see "0\n0" (grep's "0" then the fallback echo).
ICAP_ENTRY=$(docker exec "$PROXY_CID" \
    sh -c "grep -c 'ICAP.*${ICAP_TEST_DOMAIN}' /var/log/squid/exfil.log 2>/dev/null; true")

if [ "${ICAP_ENTRY:-0}" -gt 0 ]; then
    pass "Token exfiltration (ICAP body): blocked and recorded in exfil.log"
else
    fail "Token exfiltration (ICAP body): expected ICAP entry for ${ICAP_TEST_DOMAIN} in exfil.log, got none"
fi

# Remove ICAP test domain from allowlist.
ALLOWLIST_TMP=$(mktemp)
grep -v "^${ICAP_TEST_DOMAIN}$" "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}" > "$ALLOWLIST_TMP" || true
mv "$ALLOWLIST_TMP" "${PROJECT_DIR}/config/${PROJECT_ALLOWLIST_FILE}"

echo ""

# ── 17. Token exfiltration — GitHub infrastructure exemption ─────────────────
#
# Verify that a GitHub token sent to GitHub's own API is NOT flagged as exfil.
# Tokens to .github.com are legitimate — the exemption in the ACL and ICAP
# scanner must allow these through without adding entries to exfil.log.

echo "── 17. Testing GitHub infrastructure exemption (no false positive)..."

# Record the current exfil.log line count as a baseline.
# Use sh -c so the redirection runs inside the container, not on the host shell.
EXFIL_BASELINE=$(docker exec "$PROXY_CID" \
    sh -c "wc -l < /var/log/squid/exfil.log 2>/dev/null || echo 0" | tr -d '[:space:]')

# Make a request to api.github.com with a fake token header.
# The request will return 401 Unauthorized from GitHub (fake token), but the
# proxy must not add an exfil entry for it.
run_online "curl -sf --max-time 10 \
    -H 'Authorization: token ${FAKE_TOKEN}' \
    https://api.github.com/zen -o /dev/null 2>/dev/null" || true
sleep 2

EXFIL_AFTER=$(docker exec "$PROXY_CID" \
    sh -c "wc -l < /var/log/squid/exfil.log 2>/dev/null || echo 0" | tr -d '[:space:]')

if [ "${EXFIL_AFTER}" -le "${EXFIL_BASELINE}" ]; then
    pass "GitHub infra exemption: token to api.github.com not recorded in exfil.log"
else
    # Check if the new entry is actually for github.com
    NEW_ENTRIES=$(docker exec "$PROXY_CID" \
        tail -n "$((EXFIL_AFTER - EXFIL_BASELINE))" /var/log/squid/exfil.log 2>/dev/null || echo "")
    if echo "$NEW_ENTRIES" | grep -q "github\.com"; then
        fail "GitHub infra exemption: exfil.log gained github.com entries (false positive)"
    else
        pass "GitHub infra exemption: new exfil.log entries are unrelated to github.com"
    fi
fi

echo ""

# ── Results ───────────────────────────────────────────────────────────────────

echo "════════════════════════════════════════"
echo "  Results: ${PASS} passed, ${FAIL} failed"
echo "════════════════════════════════════════"

if [ ${#ERRORS[@]} -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "  ✗ ${err}"
    done
    echo ""
fi

[ "$FAIL" -eq 0 ]
