#!/usr/bin/env bash
set -e

# ---------------------------------------------------------------------------
# Install the ssl_bump CA certificate into the system trust store.
# The CA cert is generated by install.sh on the host and mounted read-only
# at /etc/squid/ca/ca.crt (single-file bind-mount from ./config/ca.crt).
# Without this step, all HTTPS connections through the proxy would fail with
# a certificate verification error ("self-signed certificate in certificate
# chain") because the copilot container sees Squid's dynamically generated
# leaf certs, which are signed by our CA.
# Skipped gracefully if the cert is absent (e.g., running without the proxy).
#
# NOTE: update-ca-certificates accepts only --verbose and --fresh flags.
#       The -q flag is not valid and causes the command to print usage and
#       exit without installing anything.
# ---------------------------------------------------------------------------
if [ -f /etc/squid/ca/ca.crt ]; then
    cp /etc/squid/ca/ca.crt \
        /usr/local/share/ca-certificates/sandboxed-copilot-ca.crt
    update-ca-certificates --fresh > /dev/null 2>&1
    if [ ! -f /etc/ssl/certs/sandboxed-copilot-ca.pem ]; then
        echo "WARNING: CA cert installation may have failed — HTTPS through proxy may not work" >&2
    fi
fi

# Persist shell history across sessions via the shell-history named volume.
export PROMPT_COMMAND='history -a'
mkdir -p "$(dirname "${HISTFILE:-$HOME/.bash_history}")"

# Fix git credential helper for cross-platform use.
#
# The host ~/.gitconfig may contain a credential.helper pointing to a macOS
# binary (e.g. /opt/homebrew/bin/gh) that does not exist inside the container.
# We create a wrapper gitconfig that:
#   1. Includes the host config (preserving name, email, aliases, etc.)
#   2. Resets credential.helper to an empty string (clears the macOS value)
#   3. Sets credential.helper to the container's gh CLI
#
# GIT_CONFIG_GLOBAL overrides the default ~/.gitconfig path so git (and all
# tools it spawns) pick up the wrapper automatically.
if [ -f "${HOME}/.gitconfig" ]; then
    # Find gh so the credential helper works regardless of PATH ordering.
    GH_BIN=$(command -v gh 2>/dev/null || echo "/usr/bin/gh")
    cat > "${HOME}/.gitconfig.container" <<EOF
[include]
    path = ${HOME}/.gitconfig
[credential]
    helper =
    helper = !${GH_BIN} auth git-credential
EOF
    export GIT_CONFIG_GLOBAL="${HOME}/.gitconfig.container"
fi

# Welcome banner — only shown for interactive sessions, not for non-interactive
# commands like `sandboxed-copilot gh copilot suggest "..."`.
if [ -t 0 ] && [ -t 1 ]; then
    ruby_ver=$(ruby --version 2>/dev/null | cut -d' ' -f2 || echo "n/a")
    python_ver=$(python --version 2>/dev/null | cut -d' ' -f2 || echo "n/a")
    node_ver=$(node --version 2>/dev/null | cut -c2- 2>/dev/null || echo "n/a")
    if [ -n "${GITHUB_TOKEN:-}" ]; then
        gh_login=$(gh api /user --jq .login 2>/dev/null || true)
    fi
    if [ -n "${gh_login:-}" ]; then
        auth_line="✓ Authenticated as @${gh_login}"
    else
        auth_line="⚠  Not authenticated — set GITHUB_TOKEN on the host"
    fi
    echo ""
    echo "  --- sandboxed-copilot --------------------------------------------------"
    echo "  Workspace  $PWD"
    printf "  Tools      ruby %-10s python %-10s node %-10s mise\n" \
        "$ruby_ver" "$python_ver" "$node_ver"
    echo "  Auth       ${auth_line}"
    echo "  Proxy      active  (from host: sandboxed-copilot proxy status)"
    echo "  ------------------------------------------------------------------------"
    echo "  Type 'exit' or Ctrl-D to return to your host shell."
    echo ""
    # Hint if the project has mise config that might need runtime installation.
    if [ -f /workspace/.mise.toml ] || [ -f /workspace/.tool-versions ]; then
        echo "  ℹ  Project has mise config — run 'mise install' to set up runtimes."
        echo ""
    fi
fi

exec "$@"
