#!/usr/bin/env bash
set -e

ALLOWLIST="/etc/squid/config/allowlist.txt"
# PROJECT_ALLOWLIST_FILE is injected by the launcher per session so concurrent
# sessions each write to their own file and don't clobber each other.
PROJECT_ALLOWLIST="/etc/squid/config/${PROJECT_ALLOWLIST_FILE:-project-allowlist.txt}"
MODE_FILE="/etc/squid/config/.mode"
ACCESS_RULES="/etc/squid/access_rules.conf"
MERGED_ALLOWLIST="/etc/squid/merged_allowlist.txt"
LOG_DIR="/var/log/squid"

# Minimum domains required for the Copilot CLI to function (used in lock mode).
LOCK_DOMAINS=".github.com .githubusercontent.com .githubcopilot.com default.exp-tas.com"

# Pre-create log files owned by the 'proxy' user that squid drops privileges to.
mkdir -p "$LOG_DIR"
touch "${LOG_DIR}/access.log" "${LOG_DIR}/cache.log" "${LOG_DIR}/exfil.log"
chown proxy:proxy "${LOG_DIR}" "${LOG_DIR}/access.log" "${LOG_DIR}/cache.log" "${LOG_DIR}/exfil.log"

# ---------------------------------------------------------------------------
# Preflight: verify the CA cert and key are present.
# They are generated by install.sh and mounted read-only from the host
# config directory. If they are absent it means install.sh has not been run
# (or has not been re-run after updating to a version with ssl_bump support).
# ---------------------------------------------------------------------------
if [ ! -f /etc/squid/config/ca.crt ] || [ ! -f /etc/squid/config/ca.key ]; then
    echo "[proxy] ERROR: CA certificate not found at /etc/squid/config/ca.crt (or ca.key)."
    echo "[proxy] Run install.sh to generate the per-install CA certificate, then restart."
    exit 1
fi

# ---------------------------------------------------------------------------
# Initialise the ssl_db certificate cache.
# Squid's security_file_certgen stores dynamically generated leaf certificates
# here. The directory must exist and be initialised before Squid starts.
# The 'proxy' user owns the directory because Squid drops privileges to it.
#
# IMPORTANT: SSL_DB must be a SUBDIRECTORY of the ssl-db Docker volume mount
# (/var/lib/ssl_db). If we used the mount point itself, security_file_certgen
# would fail with EEXIST (mkdir on an already-existing directory), leaving the
# db uninitialized and causing Squid's sslcrtd_program helper to crash.
# ---------------------------------------------------------------------------
SSL_DB="/var/lib/ssl_db/db"

# ---------------------------------------------------------------------------
# Detect CA cert rotation: if the CA cert fingerprint has changed since the
# ssl_db was last initialised, the cached leaf certs are signed by the old CA
# key and will fail verification. Clear the ssl_db so they are regenerated.
# ---------------------------------------------------------------------------
CA_FINGERPRINT_FILE="/var/lib/ssl_db/ca_fingerprint"
CURRENT_CA_FP=$(openssl x509 -in /etc/squid/config/ca.crt -fingerprint -noout 2>/dev/null | cut -d= -f2)

if [ -d "${SSL_DB}" ] && [ -f "${CA_FINGERPRINT_FILE}" ]; then
    STORED_CA_FP=$(cat "${CA_FINGERPRINT_FILE}" 2>/dev/null || echo "")
    if [ "${CURRENT_CA_FP}" != "${STORED_CA_FP}" ]; then
        echo "[proxy] CA cert has changed — clearing stale ssl_db cache..."
        rm -rf "/var/lib/ssl_db/db" "/var/lib/ssl_db/ca_fingerprint"
    fi
fi

if [ ! -d "${SSL_DB}" ]; then
    echo "[proxy] Initialising ssl_db cert cache..."
    if ! /usr/lib/squid/security_file_certgen -c -s "$SSL_DB" -M 4MB; then
        echo "[proxy] ERROR: ssl_db initialisation failed. Squid will not start."
        exit 1
    fi
    # Record the CA fingerprint so we can detect future CA cert rotation.
    echo "${CURRENT_CA_FP}" > "${CA_FINGERPRINT_FILE}"
fi
chown -R proxy:proxy "/var/lib/ssl_db" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Start the ICAP token exfiltration scanner.
# The scanner listens on 127.0.0.1:1344 and inspects POST/PUT/PATCH request
# bodies for GitHub token patterns. It appends detection events to exfil.log.
# It must be running BEFORE squid starts (squid verifies ICAP on startup with
# bypass=off; a missing scanner would prevent squid from starting).
# ---------------------------------------------------------------------------
echo "[proxy] Starting ICAP token scanner..."
/usr/local/bin/icap-scanner >> "${LOG_DIR}/exfil.log" 2>&1 &
ICAP_PID=$!

# Give the scanner a moment to bind its port, then verify it is still running.
sleep 1
if ! kill -0 "$ICAP_PID" 2>/dev/null; then
    echo "[proxy] ERROR: ICAP scanner failed to start. Check exfil.log for details."
    exit 1
fi
echo "[proxy] ICAP scanner started (pid ${ICAP_PID})"

# ---------------------------------------------------------------------------
# write_access_rules <mode>
#   Merges allowlist sources into a single file squid reads, then writes
#   access_rules.conf for the given mode. Using a single merged file avoids
#   squid silent-failure issues with multi-file dstdomain ACLs.
# ---------------------------------------------------------------------------
write_access_rules() {
    local mode="$1"

    # Always regenerate the merged allowlist so squid always reads a single,
    # fully-resolved file regardless of which source changed.
    cat "$ALLOWLIST" "$PROJECT_ALLOWLIST" 2>/dev/null > "$MERGED_ALLOWLIST" || true

    case "$mode" in
        allow-all)
            cat > "$ACCESS_RULES" <<'EOF'
# ALLOW-ALL MODE — proxy is fully open. This mode expires automatically.
# Safe_ports: deny plain HTTP to non-standard ports (belt-and-suspenders).
acl Safe_ports port 80 443
http_access deny !Safe_ports
http_access allow all
EOF
            echo "[proxy] Mode: allow-all — all outbound traffic permitted"
            ;;
        lock)
            # shellcheck disable=SC2086
            cat > "$ACCESS_RULES" <<EOF
# LOCK MODE — only the minimum domains required for Copilot CLI are reachable.
# CONNECT is restricted to port 443 to prevent SSH/non-HTTPS tunnelling.
# Safe_ports: deny plain HTTP to non-standard ports.
acl SSL_ports port 443
acl Safe_ports port 80 443
acl copilot_minimum dstdomain ${LOCK_DOMAINS}
http_access deny !Safe_ports
http_access allow CONNECT SSL_ports copilot_minimum
http_access allow copilot_minimum
http_access deny all
EOF
            echo "[proxy] Mode: lock — restricted to minimum Copilot domains"
            ;;
        *)
            cat > "$ACCESS_RULES" <<EOF
# NORMAL MODE — outbound access controlled by the merged allowlist.
# CONNECT is restricted to port 443 to prevent SSH/non-HTTPS tunnelling.
# Safe_ports: deny plain HTTP to non-standard ports.
acl SSL_ports port 443
acl Safe_ports port 80 443
acl allowed_domains dstdomain "${MERGED_ALLOWLIST}"
http_access deny !Safe_ports
http_access allow CONNECT SSL_ports allowed_domains
http_access allow allowed_domains
http_access deny all
EOF
            echo "[proxy] Mode: normal — using user allowlist"
            ;;
    esac
}

# ---------------------------------------------------------------------------
# read_mode
#   Reads the current mode from MODE_FILE. Handles allow-all expiry.
# ---------------------------------------------------------------------------
read_mode() {
    if [ ! -f "$MODE_FILE" ]; then
        echo "normal"
        return
    fi

    local content
    content=$(cat "$MODE_FILE" 2>/dev/null || echo "")

    if [[ "$content" == allow-all:* ]]; then
        local expiry="${content#allow-all:}"
        local now
        now=$(date +%s)
        if [ "$now" -lt "$expiry" ]; then
            echo "allow-all"
        else
            echo "[proxy] allow-all expired — reverting to normal allowlist" >&2
            echo "normal"
        fi
    elif [ "$content" = "lock" ]; then
        echo "lock"
    else
        echo "normal"
    fi
}

# Write initial access rules before squid starts
write_access_rules "$(read_mode)"

# Initialise squid cache directories
echo "[proxy] Initialising squid..."
squid -z --foreground 2>/dev/null || true

# Stream squid log files to Docker stdout so `docker compose logs` works.
tail -qF "${LOG_DIR}/access.log" "${LOG_DIR}/cache.log" "${LOG_DIR}/exfil.log" 2>/dev/null &

# ---------------------------------------------------------------------------
# watch_config
#   Polls every 5 seconds for changes to the mode file or allowlist.
#   Regenerates access_rules.conf and reconfigures squid as needed.
# ---------------------------------------------------------------------------
watch_config() {
    local last_mode=""
    local last_allowlist_hash=""
    last_mode=$(read_mode)
    last_allowlist_hash=$(cat "$ALLOWLIST" "$PROJECT_ALLOWLIST" 2>/dev/null | md5sum | cut -d' ' -f1)

    while true; do
        sleep 5

        local current_mode
        current_mode=$(read_mode)

        local current_allowlist_hash
        current_allowlist_hash=$(cat "$ALLOWLIST" "$PROJECT_ALLOWLIST" 2>/dev/null | md5sum | cut -d' ' -f1)

        if [ "$current_mode" != "$last_mode" ] || \
           { [ "$current_mode" = "normal" ] && [ "$current_allowlist_hash" != "$last_allowlist_hash" ]; }; then
            write_access_rules "$current_mode"
            squid -k reconfigure 2>/dev/null || true
            last_mode="$current_mode"
        fi

        last_allowlist_hash="$current_allowlist_hash"
    done
}

watch_config &

echo "[proxy] Starting squid on port 3128..."
exec squid -N -f /etc/squid/squid.conf
